### PR TITLE
Tested with SS 4.0.x

### PR DESCRIPTION
**Pull request by blueo**
We'd like to use this in a 4.0.x project and it is currently tagged as -beta.

### CODE REVIEW

**Comment by blueo** [comment]
hmm if I'm reading it correctly this error seems like scrutinizr needs a newer version of composer

**Comment by blueo** [comment]
updated scrutinizer based on this ticket: https://github.com/scrutinizer-ci/scrutinizer/issues/399. I left the previously defined checks in place but I'm not 100% sure they are applicable in the new setup so open to suggestions

**Comment by blueo** [comment]
@sminnee any problems changing the tag from beta? Also adds some updated scrutinizr config and changes to vendor module.

**Comment by sminnee** [comment]
Sorry I missed this - in future feel free to slack me ;-) reviewing now

**Review by sminnee — APPROVED** [review]

**Pull request merged**
